name: 'publish-linux-appimage'

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  publish-tauri:
    permissions:
      contents: write
    runs-on: ubuntu-latest # El host moderno y disponible de GitHub
    container:
      image: ubuntu:20.04 # El entorno aislado con GLIBC 2.31
    steps:
      # 1. Instalar herramientas de sistema (Desactivando diálogos interactivos)
      - name: Install system package dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt-get update
          apt-get install -y curl git build-essential wget file libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev libwebkit2gtk-4.0-dev

      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Instalar pnpm en el contenedor
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      # 3. Instalar Node y decirle que use el caché de pnpm
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install Frontend Dependencies
        run: pnpm install 

      - name: Build Tauri AppImage
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # El Escudo de Artefactos para descarga manual directa
      - name: Upload AppImage Artifact (Safety Net)
        uses: actions/upload-artifact@v4
        with:
          name: metv-linux-appimage
          path: src-tauri/target/release/bundle/appimage/*.AppImage